""" This script sends a reflective email to my email on Friday, and a Birthday message on my birthday """
""" This script is used online in python-anywhere to run in the cloud rather than having to run everyday """

import smtplib
import datetime as dt

# Today's details
now = dt.datetime.now()
now_tuple = (now.month, now.day)

# Birthday details
date_of_birth = dt.datetime(year=1995, month=4, day=29)
date_of_birth_tuple = (date_of_birth.month, date_of_birth.day)

# Check if it's my bday
if date_of_birth_tuple == now_tuple:
    # Test account for less security threat
    my_email = "testaccount838@yahoo.com"
    password = 'oneetwothree()'
    app_password = 'uuszxktahtvkmlun' # generated by yahoo

    # Connect to yahoo mail server
    with smtplib.SMTP("smtp.mail.yahoo.com") as connection:
        # Network security, methods are pretty self explanatory.
        connection.starttls()
        connection.login(user=my_email, password=app_password)
        connection.sendmail(from_addr=my_email, to_addrs='ciaran.19952@gmail.com',
                            msg="Subject:Happy Birthday! \n\n I wonder if we have any papers published by now?")

# Check if it's Friday
elif now.weekday() == 4:
    my_email = "testaccount838@yahoo.com"
    password = 'oneetwothree()'
    app_password = 'uuszxktahtvkmlun' # generated by yahoo

    with smtplib.SMTP("smtp.mail.yahoo.com") as connection:
        connection.starttls()
        connection.login(user=my_email, password=app_password)
        connection.sendmail(from_addr=my_email, to_addrs='ciaran.19952@gmail.com',
                            msg="Subject:Happy Friday! \n\n Did this week make you happy? \n Did the frustrating stuff really matter?")


